name: update gadpp profile page

on:
    schedule:
        - cron: "0 */12 * * *" # Run automatically every 12 hours
    workflow_dispatch: # Allows manual triggering
    push: # Runs on every push to the main branch
        branches:
            - main

jobs:
    update-profile:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: main
                  token: ${{ secrets.API_TOKEN_GITHUB }}

            - name: Sync main to master
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git fetch origin
                  git checkout -B master
                  git push -f origin master

            - name: Change default branch to master temporarily
              run: |
                  curl -L \
                    -X PATCH \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/${{ github.repository }} \
                    -d '{"default_branch":"master"}'
                  sleep 3

            - name: Update profile with GADPP
              uses: umutphp/github-action-dynamic-profile-page@v5
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  github-username: "vancenceho"
                  user-email: "vancence_ho@mymail.sutd.edu.sg"

            - name: Sync master changes back to main
              if: always()
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git fetch origin
                  git checkout main
                  git reset --hard origin/master
                  git push -f origin main

            - name: Restore default branch to main
              if: always()
              run: |
                  curl -L \
                    -X PATCH \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/${{ github.repository }} \
                    -d '{"default_branch":"main"}'
